# Generated by Django 3.1.5 on 2021-02-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='households',
            name='cameFrom',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'Rural'), ('2', 'Urban')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='households',
            name='disability',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'Seeing'), ('2', 'Hearing'), ('3', 'Speech'), ('4', 'Movement'), ('5', 'Mental-Retardness'), ('6', 'Mental-Illness'), ('7', 'Multiple-Disability'), ('8', 'Other')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='households',
            name='dob',
            field=models.DateField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='households',
            name='highestEDUAttained',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'School'), ('2', 'College'), ('3', 'Vocational'), ('4', 'Special Institution For Disabled'), ('5', 'Literacy-Centre'), ('6', 'Other-Institution'), ('7', 'None')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='households',
            name='martialStatus',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'Never-Married'), ('2', 'Currently-Married'), ('3', 'Widowed'), ('4', 'Separated'), ('5', 'Divorced')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='households',
            name='modeOfTravel',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'On Foot'), ('2', 'Bicycle'), ('3', 'Moped/Scooter/Motor-Cycle'), ('4', 'Car/Jeep/VAN  '), ('5', 'Literacy Centre'), ('6', 'Other Institution'), ('7', 'None')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='households',
            name='motherTongue',
            field=models.CharField(default='Hindi', max_length=1000),
        ),
        migrations.AlterField(
            model_name='households',
            name='nonWorkerType',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'Student'), ('2', 'Household-Duties'), ('3', 'Dependent'), ('4', 'Pensioner'), ('5', 'Rentier'), ('6', 'Beggar'), ('7', 'Other')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='households',
            name='religion',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'Hindu'), ('2', 'Muslim'), ('3', 'Christian'), ('4', 'Sikh'), ('5', 'Buddhist'), ('6', 'Jain')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='households',
            name='scst',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'SC'), ('2', 'ST'), ('3', 'Other')], max_length=1001000),
        ),
        migrations.AlterField(
            model_name='households',
            name='sex',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'Female'), ('2', 'Male'), ('3', 'Other')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='households',
            name='workedAs',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'Employer'), ('2', 'Employee'), ('3', 'Single-Worker'), ('4', 'Family-Worker')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='households',
            name='workedLike',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'Main-Worker'), ('2', 'Marginal-Worker'), ('3', 'Non-Worker')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='households',
            name='workerClass',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'Employer'), ('2', 'Employee'), ('3', 'Single-Worker'), ('4', 'Family-Worker')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='BathingFacility',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'YES, Bathroom'), ('2', 'YES, Enclosure without roof'), ('3', 'NO')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='CensusHouseNo',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='Cereal',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'Rice'), ('2', 'Wheat'), ('3', 'Jowar'), ('4', 'Bajra'), ('5', 'Maize'), ('6', 'Any other')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='ComputingDevice',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'YES'), ('2', 'NO')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='ContactNo',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='DrinkingWaterAvail',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'Within premises'), ('2', 'Near the premises'), ('3', 'Away')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='DrinkingWaterSource',
            field=models.CharField(choices=[('0', 'Other sources'), ('1', 'Tap water from source'), ('2', 'Tap water from un-treated source'), ('3', 'Well'), ('4', 'Hand Pump'), ('5', 'Tubewell/ borehole'), ('6', 'Spring'), ('7', 'River/canal'), ('8', 'Tank/pond/lake'), ('9', 'Packaged/bottled water')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='FloorMaterial',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'Mud'), ('2', 'Wood/bamboo'), ('3', 'Burnt brick'), ('4', 'Stone'), ('5', 'Cement'), ('6', 'Mosaic/floor tiles'), ('7', 'Any other')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='FourWheeler',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'YES'), ('2', 'NO')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='HeadCaste',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'SC'), ('2', 'ST'), ('3', 'Other')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='HeadSex',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'Female'), ('2', 'Male'), ('3', 'Other')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='Internet',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'YES, On laptop/computer'), ('2', 'YES, On mobile/smartphone'), ('3', 'YES, On any other device'), ('4', 'NO')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='Kitchen',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'Cooking in kitchen, has LPG/PNG Connection'), ('2', 'Cooking in kitchen, Does not have LPG/PNG Connection'), ('3', 'Cooking inside house, but not in kitchen, Has LPG/PNG Connection'), ('4', 'Cooking inside house, but not in kitchen, does not have LPG/PNG Connection'), ('5', 'Cooking in open/ outside house, Has LPG/PNG Connection'), ('6', 'Cooking in open/ outside house, does not have LPG/PNG Connection'), ('7', 'No cooking')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='KitchenFuel',
            field=models.CharField(choices=[('0', 'Any other'), ('1', 'Firewood'), ('2', 'Crop residue'), ('3', 'Cowding cake'), ('4', 'Coal/lignite/charcoal'), ('5', 'Kerosene'), ('6', 'LPG/PNG'), ('7', 'Electricity'), ('8', 'Bio-gas'), ('9', 'Solar')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='LatrineAccess',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'YES, Exclusively for household use only'), ('2', 'YES, Shared with other household'), ('3', 'YES, Public latrine'), ('4', 'NO, Open')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='LatrineType',
            field=models.CharField(choices=[('0', 'Night soil disposed into open drain'), ('1', 'Flush/pour flush latrine connected to Piped sewer system'), ('2', 'Flush/pour flush latrine connected to Septic tack'), ('3', 'Flush/pour flush latrine connected to Other system'), ('4', 'Twin Pit latrine With slab/ventilated improved pit'), ('5', 'Twin Pit latrine Without slab/open pit'), ('6', 'Single Pit latrine With slab/ventilated improved pit'), ('7', 'Single Pit latrine Without slab/open pit'), ('8', 'Service latrine Night soil removed by human'), ('9', 'Service latrine Night soil serviced by animals')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='LightingSource',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'Electricity'), ('2', 'Kerosene'), ('3', 'Solar'), ('4', 'Other oil'), ('5', 'Any other'), ('6', 'No lighting')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='Ownership',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'Owned'), ('2', 'Rented but has own house elsewhere'), ('3', 'Rented and does not own any house'), ('4', 'Any other')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='Phone',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'YES, Landline only'), ('2', 'YES, Mobile only, Smartphone'), ('3', 'YES, Mobile only, Other basic mobile'), ('4', 'YES, Both'), ('5', 'No')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='Radio',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'YES, Traditional radio set'), ('2', 'YES, on mobile/smartphone'), ('3', 'YES, On any other device'), ('4', 'NO')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='RoofMaterial',
            field=models.CharField(choices=[('0', 'Any other'), ('1', 'Grass/ thatch/ bamboo/ wood/ mud'), ('2', 'Plastic/ polythene'), ('3', 'Hand made tiles'), ('4', 'Machine made tiles'), ('5', 'Burnt brick'), ('6', 'Stone'), ('7', 'Slate'), ('8', 'G.I./metal/asbestos sheets'), ('9', 'Concrete')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='Television',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'YES, Doordarshan free dish'), ('2', 'YES, DTH/Dish'), ('3', 'YES, Cable connection'), ('4', 'Any other'), ('5', 'NO')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='TwoWheeler',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'Bicycle'), ('2', 'Scooter/ Motorcycle/ Moped'), ('3', 'Both'), ('4', 'None')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='UseOfHouse',
            field=models.CharField(choices=[('0', 'Any other'), ('1', 'Residence'), ('2', 'Residence-cum-other use'), ('3', 'Shop/ office'), ('4', 'School/ college'), ('5', 'Hotel/ lodge/ guest house'), ('6', 'Hospital/ dispensary'), ('7', 'Factory/ workshop/ workshed'), ('8', 'Place of worship'), ('9', 'Other non-residential use')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='WallMaterial',
            field=models.CharField(choices=[('0', 'Any other'), ('1', 'Grass/thatch/bamboo'), ('2', 'Plastic/polythene'), ('3', 'Mud/unburnt brick'), ('4', 'Wood'), ('5', 'Stone not packed with mortar'), ('6', 'Stone packed with mortar'), ('7', 'G.I./metal/asbestos sheets'), ('8', 'Burnt brick'), ('9', 'Concrete')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='WasteWaterOutlet',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'Closed drainage'), ('2', 'Open drainage'), ('3', 'No drainage')], max_length=1000),
        ),
    ]
