# Generated by Django 3.1.6 on 2021-02-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyor', '0002_auto_20210214_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='houselisting',
            name='district',
            field=models.CharField(default='Pune', max_length=100),
        ),
        migrations.AddField(
            model_name='houselisting',
            name='state',
            field=models.CharField(default='UP', max_length=100),
        ),
        migrations.AddField(
            model_name='houselisting',
            name='subDistrict',
            field=models.CharField(default='chincwad', max_length=100),
        ),
        migrations.AddField(
            model_name='houselisting',
            name='village',
            field=models.CharField(default='chincwad', max_length=100),
        ),
        migrations.AddField(
            model_name='houselisting',
            name='wardNo',
            field=models.IntegerField(default=0),
        ),
    ]
