# Generated by Django 3.1.5 on 2021-02-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyor', '0003_auto_20210214_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='households',
            name='workedAs',
            field=models.CharField(choices=[('-1', '-1'), ('1', 'Cultivator'), ('2', 'Agricultural-Labourer'), ('3', 'Work In household industry'), ('4', 'Other')], max_length=1000),
        ),
    ]
